### ISSUE TITLE
Include Promise.prototype.reflect

### ISSUE THREAD

**Issue by Ginden** [jasonwilliams/proposal-promise-allSettled#6]
Idea: add `Promise.prototype.reflect` based on [Bluebird `.reflect`](http://bluebirdjs.com/docs/api/reflect.html).
Then, `allSettled` can be defined in terms of applying `PromiseResolve` on all items in array, and calling `reflect` method on all of them.

**Comment by ljharb** [comment]
If reflect exists, then settleAll seems to have little value because you can `Promise.all(promises.map(x => x.reflect()))`.

**Comment by mathiasbynens** [comment]
This was discussed at today’s TC39 meeting, and the conclusion was that there’s no real-world use case. From @domenic’s experience with Q, it seems that people really only want to use `allSettled`. We should probably wait until someone comes up with a real userland use case before we expose `reflect`/`inspect`. Closing for now.
